### ISSUE TITLE
Handle if/else statements

### ISSUE THREAD

**Issue by matthewdavidson** [Skyscanner/stylelint-config-skyscanner#4]
`stylelint-config-skyscanner` complains that the following scss is invalid:
```scss
  @if $direction == 'left' {
    left: 0;
  } @else {
    right: 0;
  }
```
...and suggest that I do this:
```scss
  @if $direction == 'left' {
    left: 0;
  }

  @else {
    right: 0;
  }
```
